### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by notAreYouScared** [JN-Jones/JonesCore#1]
Parse error: syntax error, unexpected ':' in /inc/plugins/jones/core/Alerts.php on line 220

Just a common  typo, should be ;

**Comment by JN-Jones** [comment]
That should be fixed with 1.0.2 (fixed with the latest commit https://github.com/JN-Jones/JonesCore/blob/master/inc/plugins/jones/core/Alerts.php#L220)
